sudo: required
dist: trusty
before_install:
  - gem install bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - jruby
gemfile:
  - Gemfile
  - gemfiles/i18n_0.4.gemfile
  - gemfiles/i18n_0.5.gemfile
  - gemfiles/i18n_0.6.gemfile
  - gemfiles/i18n_0.7.gemfile
notifications:
  slack:
    secure: JryUWfe2JR0cfNT+TIHwryy8NS8m9/hbRhg+5UqwuYWuEp6gtcWCA05wKsajQyRrGaNGYKu81RA9jpQrirgQWzDUJl5o3sEWbqKZv3pW0ybn8Tx52N1mxW3Puar5KLZ8TPRphKKIJ8/1EhAh4zpC5Mtxv8Sz1/AHuqnlu6l+bb4=
